
namespace CSC237_ContactMgr14_start.Models
{
    public class Category
    {
        // primary key - generated by database
        public int CategoryId { get; set; }
        public string Name { get; set; }
    }
}
